# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: 'Explainable AI for SE'
author: Chakkrit Tantithamthavorn and Jirayus Jiarpakdee
logo: logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: cache
  run_in_temp: true
#   execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/xai4se/book  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
# html:
#   use_issues_button: true
#   use_repository_button: true
#   home_page_in_navbar: false
#   use_edit_page_button: true
#   baseurl: https://analytics-cookbook.github.io

#######################################################################################
# HTML-specific settings
html:
#   favicon                   : "./_static/images/logo/favicon.ico"  # A path to a favicon image
  navbar_number_sections    : true  # Add a number to each section in your left navbar
  use_edit_page_button      : true  # Whether to add an "edit this page" button to pages. If `true`, repository information in repository: must be filled in
  use_repository_button     : true  # Whether to add a link to your repository button
  use_issues_button         : true  # Whether to add an "open an issue" button
  home_page_in_navbar       : true  # Whether to include your home page in the left Navigation Bar
  baseurl                   : "https://xai4se.github.io/book"  # The base URL where your book will be hosted.
#   extra_navbar              : Powered by <a href="https://jupyterbook.org">Jupyter Book</a>  # Will be displayed underneath the left navbar.
  extra_footer              :   # Will be displayed underneath the footer.
    <script>mermaid.init();</script>
    <div class="row_footer">
    This project has received funding from the <a href="https://www.arc.gov.au/">Australian Research Council</a>'s Discovery Early Career Researcher Award (ARC DECRA) funding scheme (DE200100941). This book reflects the views of the authors and neither Australian Research Council nor Monash University are liable for any use that may be made of the information contained herein. The content of this project is licensed under the Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License. The source code that is part of the content, as well as the source code used to format and display that content is licensed under the MIT License.
    </div>
  google_analytics_id       : "UA-54962993-1"  # A GA id that can be used to track book views.
#   comments:
#     hypothesis: true
#     utterances:
#       repo: "analytics-cookbook/analytics-cookbook.github.io"
#######################################################################################

launch_buttons:
  notebook_interface: "jupyterlab" # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url: "https://mybinder.org"
  colab_url: "https://colab.research.google.com"
#   thebe: true
